apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    sever: mongodb
    tier: db
spec: 
  containers:
    - name: nginx
      image: macharavikishore/mongodb:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 27017 
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"  
        limits:
          memory: "128Mi"
          cpu: "250m"  

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    sever: mongodb
    tier: db

  ports:
   - port: 27017
     targetPort: 27017