apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    server: mongodb  # Corrected label key
    tier: db
spec:
  containers:
    - name: mongodb  # Corrected container name to match the image
      image: macharavikishore/mongodb:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 27017


---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    server: mongodb
    tier: db
  ports:
    - port: 27017
      targetPort: 27017
