apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
data:
  MONGO_URL: "mongodb://mongodb:27017/catalogue"  # Corrected MongoDB port

---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    server: catalogue  # Corrected label key
    tier: app
spec:
  containers:
    - name: catalogue
      image: macharavikishore/catalogue:k8
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: catalogue-config  # Corrected indentation
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    server: catalogue
    tier: app
  ports:
    - port: 80
      targetPort: 8080
