apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  MONGO_URL: "mongodb://mongodb:27017/user"
  REDIS_HOST: "redis" # Corrected MongoDB port

---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    server: user  # Corrected label key
    tier: app
spec:
  containers:
    - name: user
      image: macharavikishore/user:v1
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: user-config  # Corrected indentation
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    server: user
    tier: app
  ports:
    - port: 80
      targetPort: 8080
