apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    web: roboshop
    tier: frontend
spec: 
  containers:
    - name: nginx
      image: macharavikishore/web:k8
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"  
        limits:
          memory: "128Mi"
          cpu: "250m"  

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    web: roboshop
    tier: frontend
  ports:
   - port: 80
     targetPort: 80
